CREATE DATABASE botdb;
CREATE USER botuser WITH ENCRYPTED PASSWORD 'botpwd';
GRANT ALL PRIVILEGES ON DATABASE botdb TO botuser;

\connect botdb;

CREATE SCHEMA IF NOT EXISTS bot AUTHORIZATION botuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA bot
GRANT ALL ON TABLES TO botuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA bot
GRANT ALL ON SEQUENCES TO botuser;
